version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  commands:
    - pip install -e .
    - pip install -r docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  builder: html
